# GET all tickets from {travel}
GET {{APP_URL}}/api/v1/travels/1/tickets
Accept: application/json

# create ticket for {travel}
POST {{APP_URL}}/api/v1/travels/1/tickets
Accept: application/json
Content-Type: application/json

{
    "user_id": 1,
    "cancelled_at": null
}

# GET show {ticket} from {travel}
GET {{APP_URL}}/api/v1/travels/11/tickets/5
Accept: application/json

# edit {ticket} from {travel}
PATCH {{APP_URL}}/api/v1/travels/11/tickets/5
Accept: application/json
Content-Type: application/json

{
    "user_id": 6,
    "cancelled_at": null
}
