GET {{APP_URL}}/api/v1/travels
Accept: application/json
Authorization: Bearer {{SANCTUM_TOKEN}}

POST {{APP_URL}}/api/v1/travels
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{SANCTUM_TOKEN}}

{
  "price": "1333.3",
  "departure_time": "2022-10-23 19:46:08",
  "arrival_time": "2022-10-30 21:11:16",
  "departure_place": "Kelliehaven",
  "arrival_place": "Port Kimberly",
  "total_passengers": 40,
  "available_passengers": 40,
  "done": false
}

GET {{APP_URL}}/api/v1/travels/20
Accept: application/json
Authorization: Bearer {{SANCTUM_TOKEN}}

PATCH {{APP_URL}}/api/v1/travels/54
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{SANCTUM_TOKEN}}

{
  "price" : "1694.3",
  "departure_time" : "2022-10-23 19:46:08",
  "arrival_time" : "2022-10-30 21:11:16",
  "departure_place" : "Kelliehaven",
  "arrival_place" : "Port Kimberly",
  "total_passengers" : 69,
  "available_passengers" : 43,
  "done" : false
}

DELETE {{APP_URL}}/api/v1/travels/54
Accept: application/json
Authorization: Bearer {{SANCTUM_TOKEN}}
