# GET all travels with attached cities
GET {{APP_URL}}/api/v1/travels
Accept: application/json

# create travel with cities by name
POST {{APP_URL}}/api/v1/travels
Accept: application/json
Content-Type: application/json

{
    "travel": { 
        "price": "1333.3",
        "total_passengers": 10,
        "available_passengers": 10,
        "done": false
    },
    "cities": [
        {
            "city_travel_type_id": 1,
            "city_id": 43,
            "port_call": "2022-12-8 19:46:03"
        },
        {
            "city_travel_type_id": 2,
            "city_id": 69,
            "port_call": "2022-12-9 21:11:16"
        }
    ]
}

# GET travel by id
GET {{APP_URL}}/api/v1/travels/93
Accept: application/json

# update travel
PATCH {{APP_URL}}/api/v1/travels/2
Accept: application/json
Content-Type: application/json

{
  "price" : "1694.3",
  "total_passengers" : 8,
  "done" : true
}

# DELETE travel by id
DELETE {{APP_URL}}/api/v1/travels/2
Accept: application/json
