# GET all travels with attached cities
GET {{APP_URL}}/api/v1/travels
Accept: application/json

# create travel with cities by name
POST {{APP_URL}}/api/v1/travels
Accept: application/json
Content-Type: application/json

{
    "travel": { 
        "price": "1333.3",
        "departure_date": "2022-11-15 19:46:08",
        "arrival_date": "2022-11-17 21:11:16",
        "total_passengers": 10,
        "available_passengers": 10,
        "done": false
    },
    "cities": [
        {
            "city_travel_type_id": 1,
            "city_id": 43
        },
        {
            "city_travel_type_id": 2,
            "city_id": 69
        }
    ]
}

# GET travel by id
GET {{APP_URL}}/api/v1/travels/43
Accept: application/json

# update travel
PATCH {{APP_URL}}/api/v1/travels/2
Accept: application/json
Content-Type: application/json

{
  "price" : "1694.3",
  "departure_date" : "2022-11-14 19:46:08",
  "done" : true
}

# DELETE travel by id
DELETE {{APP_URL}}/api/v1/travels/1
Accept: application/json
