# GET user logged
GET {{APP_URL}}/api/user
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{SANCTUM_TOKEN}}

# log in
POST {{APP_URL}}/api/login

{
  "name" : "greg",
  "email" : "agreg@developer.com",
  "password" : "password"
}

# register
POST {{APP_URL}}/api/register
Accept: application/json
Content-Type: application/json

{
  "name" : "greg",
  "email" : "greg@developer.com",
  "password" : "password"
}
