GET {{APP_URL}}/api/user
Accept: application/json
Authorization: Bearer 35|THZTEL1YcGESJ08Ksjah8EBkv4DelGITxz1oEBef

POST {{APP_URL}}/api/login
Accept: application/json
Content-Type: application/json

{
  "name" : "Dr. Justice Gaylord MD",
  "email" : "verona.davis@example.org",
  "password" : "password"
}
